#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Turn a TTF into the alpha bitmaps the C shell draws text with.

    python3 tools/c/make-font.py [font.ttf] [size] [out.h] [prefix]

THERE IS NO FONT SERVER IN A FRAMEBUFFER.  The C side draws text by
compositing a coverage bitmap per glyph, so the rasterising happens once,
here, ahead of time - the same way the icon planes are made.

Only the printable ASCII range is emitted, because that is what a panel
puts on screen: a clock, a task name, a menu row.  A glyph that is not
here draws nothing rather than a box, and the caller can see that in the
coverage table.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126


def main():
    ttf = Path(sys.argv[1] if len(sys.argv) > 1
               else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 11
    out = Path(sys.argv[3] if len(sys.argv) > 3
               else "src/trait_font.h")
    prefix = sys.argv[4] if len(sys.argv) > 4 else "trait_font"

    font = ImageFont.truetype(str(ttf), size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        width = max(advance, 1)
        cell = Image.new("L", (width + 2, height), 0)
        ImageDraw.Draw(cell).text((0, 0), ch, font=font, fill=255)
        glyphs.append((code, ch, advance, width + 2,
                       list(cell.get_flattened_data())))

    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-only */",
        "/*",
        " * GENERATED by tools/c/make-font.py - do not edit.",
        " *",
        f" * {ttf.name} at {size}px, printable ASCII only.  One coverage",
        " * byte per pixel; the drawing code tints it, so a glyph carries",
        " * no colour of its own.  Metrics are the font's own:",
        f" * ascent {ascent}, descent {descent}, line {height}.",
        " */",
        f"#ifndef {prefix.upper()}_H",
        f"#define {prefix.upper()}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {prefix.upper()}_FIRST {FIRST}U",
        f"#define {prefix.upper()}_LAST {LAST}U",
        f"#define {prefix.upper()}_ASCENT {ascent}U",
        f"#define {prefix.upper()}_DESCENT {descent}U",
        f"#define {prefix.upper()}_HEIGHT {height}U",
        "",
    ]
    for code, ch, advance, width, data in glyphs:
        name = f"{prefix}_{code}"
        lines.append(f"/* {code} {ch!r} advance {advance} */")
        lines.append(f"static const uint8_t {name}[] = {{")
        row = []
        for index, value in enumerate(data):
            row.append(f"{value:4d},")
            if len(row) == 16:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
    lines.append("")
    lines.append(f"struct {prefix}_glyph {{")
    lines.append("    const uint8_t *coverage;")
    lines.append("    uint32_t width;")
    lines.append("    uint32_t advance;")
    lines.append("};")
    lines.append("")
    lines.append(f"static const struct {prefix}_glyph {prefix}[] = {{")
    for code, ch, advance, width, _ in glyphs:
        lines.append(f"    {{ {prefix}_{code}, {width}U, {advance}U }},")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif /* {prefix.upper()}_H */")
    out.write_text("\n".join(lines) + "\n")
    print(f"wrote {out}: {len(glyphs)} glyphs, {ttf.name} at {size}px, "
          f"line height {height}")


if __name__ == "__main__":
    main()
