#!/usr/bin/env python3
"""Generate src/trait_relief.h: fvwm's own relief colours for the frame.

fvwm draws every bevel in two colours computed from the background, and
the computation is not a guess - it is GetHilite() and GetShadow() in
fvwm's libs/ColorUtils.c.  This file is that function, transcribed, run
over the handful of backgrounds this desktop uses, and emitted as
constants.

It is done here rather than in C because the medium-brightness branch is
color_mult(), which converts to HLS and back in double precision.  The
desktop is built -ffreestanding -msoft-float: it has no floating point
to do that in, and a fixed-point re-derivation would be this project's
arithmetic rather than fvwm's.  Nine constants are.

Source: https://github.com/fvwmorg/fvwm  libs/ColorUtils.c
        BRIGHTNESS(r,g,b) = 2r + 3g + b
        PCT_BRIGHTNESS    = 6 * 0xffff / 100
        thresholds        15 and 85 per cent
        PCT_DARK_TOP 50, PCT_DARK_BOTTOM 70
        PCT_LIGHT_TOP 80, PCT_LIGHT_BOTTOM 55
        BRIGHTNESS_FACTOR 1.4, DARKNESS_FACTOR 0.5
"""

import sys

SCALE = 65535.0
HALF_SCALE = SCALE / 2


def color_mult(red, green, blue, k):
    """fvwm's color_mult: scale lightness and saturation by k in HLS."""
    if red == green and red == blue:
        temp = min(k * red, SCALE)
        return (temp, temp, temp)

    r, g, b = float(red), float(green), float(blue)
    if r > g:
        if r > b:
            mx = r
            if g < b:
                mn, a = g, b - g
            else:
                mn, a = b, g - b
        else:
            mx, mn, a = b, g, r - g
    else:
        if g > b:
            mx = g
            if b < r:
                mn, a = b, r - b
            else:
                mn, a = r, b - r
        else:
            mx, mn, a = b, r, g - r

    delta = mx - mn
    a = a / delta

    l = (mx + mn) / 2
    s = (mx + mn) if l <= HALF_SCALE else (2.0 * SCALE - (mx + mn))
    s = delta / s

    l = min(l * k, SCALE)
    s = min(s * k, 1.0)

    mx = l * (1 + s) if l <= HALF_SCALE else s * SCALE + l - s * l
    mn = 2 * l - mx
    delta = mx - mn
    middle = mn + delta * a

    # Put the three back in the order they came in.
    order = _order(red, green, blue)
    return _unorder(order, mx, middle, mn)


def _order(r, g, b):
    if r > g:
        if r > b:
            return "R_MAX_G_MIN" if g < b else "R_MAX_B_MIN"
        return "B_MAX_G_MIN"
    if g > b:
        return "G_MAX_B_MIN" if b < r else "G_MAX_R_MIN"
    return "B_MAX_R_MIN"


def _unorder(state, mx, middle, mn):
    return {
        "R_MAX_G_MIN": (mx, mn, middle),
        "R_MAX_B_MIN": (mx, middle, mn),
        "G_MAX_B_MIN": (middle, mx, mn),
        "G_MAX_R_MIN": (mn, mx, middle),
        "B_MAX_G_MIN": (middle, mn, mx),
        "B_MAX_R_MIN": (mn, middle, mx),
    }[state]


def relief(rgb24, light, dark, factor):
    """GetShadowOrHiliteColor, on a 24-bit colour, back to 24 bits."""
    r = ((rgb24 >> 16) & 0xFF) * 257
    g = ((rgb24 >> 8) & 0xFF) * 257
    b = (rgb24 & 0xFF) * 257

    brightness = 2 * r + 3 * g + b
    pct = 6 * 65535 / 100

    if brightness < 15 * pct:
        out = tuple(65535 - ((65535 - c) * dark + 50) // 100
                    for c in (r, g, b))
    elif brightness > 85 * pct:
        out = tuple((c * light + 50) // 100 for c in (r, g, b))
    else:
        out = color_mult(r, g, b, factor)

    return sum(int(min(max(c, 0), 65535)) // 257 << s
               for c, s in zip(out, (16, 8, 0)))


def hilite(rgb24):
    return relief(rgb24, 80, 50, 1.4)


def shadow(rgb24):
    return relief(rgb24, 55, 70, 0.5)


# The backgrounds this desktop bevels, and where each number comes from.
#
# One colour per window state rather than two.  The frame used to be an
# Openbox vertical ramp between a top and a bottom; fvwm has no gradient
# in it, so the second colour went, and what replaced it is the pair of
# relief colours fvwm would have computed from the first.
GROUNDS = (
    ("CLEARLOOKS_ACTIVE", 0x5B6472, "Clearlooks' own title bar"),
    ("CLEARLOOKS_IDLE", 0x3B3F46, "Clearlooks' unfocused title bar"),
    ("ADWAITA_ACTIVE", 0x5C616C, "Adwaita's own title bar"),
    ("ADWAITA_IDLE", 0x3C4048, "Adwaita's unfocused title bar"),
    ("ADWAITA_DARK_ACTIVE", 0x2F2F2F, "Adwaita-dark's own title bar"),
    ("ADWAITA_DARK_IDLE", 0x262626, "Adwaita-dark's unfocused title bar"),
    ("OPENRFS_ACTIVE", 0x0000FF,
     "fvwm's HilightColor #bebebe blue - the focused window"),
    ("OPENRFS_IDLE", 0x8B0000,
     "fvwm's Style \"*\" Color #bebebe/darkred - every other window"),
    ("MENU", 0xBEBEBE,
     "fvwm's MenuStyle #4d4d4d #bebebe #e7e7e7 - the root menu"),
)


def main():
    out = ["/* SPDX-License-Identifier: GPL-3.0-only */",
           "/* GENERATED by tools/make-relief.py - do not edit. */",
           "#ifndef TRAIT_RELIEF_H",
           "#define TRAIT_RELIEF_H",
           "",
           "/*",
           " * fvwm bevels every frame in two colours it computes from the",
           " * background with GetHilite() and GetShadow().  This is those",
           " * two functions, run over every ground this desktop bevels, so",
           " * the relief is fvwm's arithmetic rather than a pair of",
           " * colours that looked about right beside the first.",
           " *",
           " * Each name expands to THREE colours - ground, lit side, shadow",
           " * side - in that order, so a palette names a frame once.",
           " */"]
    for name, ground, why in GROUNDS:
        out.append("")
        out.append("/* %s */" % why)
        out.append("#define TRAIT_RELIEF_%s \\" % name)
        out.append("    0x%06XU, 0x%06XU, 0x%06XU"
                   % (ground, hilite(ground), shadow(ground)))
    out.append("")
    out.append("#endif /* TRAIT_RELIEF_H */")
    text = "\n".join(out) + "\n"
    with open("src/trait_relief.h", "w") as fh:
        fh.write(text)
    sys.stderr.write(text)


if __name__ == "__main__":
    main()
