#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Turn the OpenRFS mark into the ASCII the terminal prints.

    python3 tools/make-logo.py [mark.png] [out.h] [columns] [rows]

gfetch puts the mark beside the facts, the way every fetch has since
screenfetch, and a terminal has no pixels to put a PNG in - it has
characters.  So the mark is reduced here, once, and the C side prints
the lines.

NOT A LUMINANCE RAMP.  The obvious ' .:-=+*#%@' ramp turns this mark to
mush: the body is one flat red, so every pixel of it lands on the same
rung and the fish comes out as a featureless blob.  What makes the
drawing legible is that it has FOUR THINGS IN IT - the paper, the black
outline, the red body and the pink tongue - so each of those gets a
character and the reduction is a classification rather than a ramp.

Characters are about twice as tall as they are wide, so the rows are
asked for separately rather than derived from the width; asking for a
square grid gives you a fish squashed to half its height.
"""
import sys
from pathlib import Path

from PIL import Image

PAPER = " "      # transparent, and the white of the eyes
OUTLINE = "#"    # the black line the whole drawing is built from
BODY = "+"       # the red
TONGUE = ":"     # the pink

MAX_LINE = 64    # a fetch has to leave room for the facts beside it


def main():
    src = Path(sys.argv[1] if len(sys.argv) > 1
               else "assets/logo/openrfs-mark-512.png")
    out = Path(sys.argv[2] if len(sys.argv) > 2 else "src/trait_logo.h")
    columns = int(sys.argv[3]) if len(sys.argv) > 3 else 40
    rows = int(sys.argv[4]) if len(sys.argv) > 4 else 18

    image = Image.open(src).convert("RGBA")
    ink = image.getchannel("A").getbbox()
    if ink is None:
        sys.exit("REFUSED: %s is empty" % src.name)
    image = image.crop(ink).resize((columns, rows), Image.LANCZOS)
    pixels = image.load()

    lines = []
    for y in range(rows):
        row = []
        for x in range(columns):
            r, g, b, a = pixels[x, y]
            light = (r * 299 + g * 587 + b * 114) // 1000
            if a < 110 or light > 205:
                row.append(PAPER)
            elif light < 70:
                row.append(OUTLINE)
            elif light > 165:
                row.append(TONGUE)
            else:
                row.append(BODY)
        lines.append("".join(row).rstrip())

    if not any(line.strip() for line in lines):
        sys.exit("REFUSED: the reduction came out blank")
    if max(len(line) for line in lines) > MAX_LINE:
        sys.exit("REFUSED: %d columns leaves no room for the facts"
                 % columns)

    text = [
        "/* SPDX-License-Identifier: GPL-3.0-only */",
        "/*",
        " * GENERATED by tools/make-logo.py - do not edit.",
        " *",
        " * The OpenRFS mark at %u by %u characters, reduced from"
        % (columns, rows),
        " * %s.  See assets/logo/SOURCE.txt for" % src.name,
        " * whose drawing it is.",
        " */",
        "#ifndef TRAIT_LOGO_H",
        "#define TRAIT_LOGO_H",
        "",
        "#define TRAIT_LOGO_ROWS %uU" % len(lines),
        "#define TRAIT_LOGO_COLUMNS %uU" % columns,
        "",
        "static const char *const trait_logo[TRAIT_LOGO_ROWS] = {",
    ]
    for line in lines:
        text.append('    "%s",' % line.replace("\\", "\\\\")
                    .replace('"', '\\"'))
    text += ["};", "", "#endif /* TRAIT_LOGO_H */"]
    out.write_text("\n".join(text) + "\n")
    print("wrote %s: %u rows, widest %u characters"
          % (out, len(lines), max(len(line) for line in lines)))


if __name__ == "__main__":
    main()
