#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Turn a TTF into the bitmaps the C shell draws text with.

    python3 tools/make-font.py [font.ttf] [size] [out.h] [prefix] [--aa]

THERE IS NO FONT SERVER IN A FRAMEBUFFER.  The C side draws text by
compositing a coverage bitmap per glyph, so the rasterising happens once,
here, ahead of time - the same way the icon planes are made.

Only the printable ASCII range is emitted, because that is what a panel
puts on screen: a clock, a task name, a menu row.  A glyph that is not
here draws nothing rather than a box, and the caller can see that in the
coverage table.

Coverage is 0 or 255 unless --aa is passed.  The desktop draws in a
sixteen-colour palette with no blending anywhere else, and a letter with
forty shades along its edge is the one thing on the screen that is not
made of those sixteen.  Thresholding is what makes it a pixel font
rather than a small smooth one.
"""
import sys
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 32, 126


def main():
    ttf = Path(sys.argv[1] if len(sys.argv) > 1
               else "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf")
    size = int(sys.argv[2]) if len(sys.argv) > 2 else 11
    out = Path(sys.argv[3] if len(sys.argv) > 3
               else "src/trait_font.h")
    prefix = sys.argv[4] if len(sys.argv) > 4 else "trait_font"
    antialias = "--aa" in sys.argv

    font = ImageFont.truetype(str(ttf), size)
    ascent, descent = font.getmetrics()
    height = ascent + descent

    glyphs = []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        advance = int(round(font.getlength(ch)))
        width = max(advance, 1)
        cell = Image.new("L", (width + 2, height), 0)
        ImageDraw.Draw(cell).text((0, 0), ch, font=font, fill=255)
        data = list(cell.get_flattened_data())
        if not antialias:
            # 128 rather than a lower number: a lower one fattens every
            # stem by the half-covered pixel beside it and the face comes
            # out bold at every size.
            data = [255 if v >= 128 else 0 for v in data]
        glyphs.append((code, ch, advance, width + 2, data))

    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-only */",
        "/*",
        " * GENERATED by tools/make-font.py - do not edit.",
        " *",
        f" * {ttf.name} at {size}px, printable ASCII only.  One coverage",
        " * byte per pixel; the drawing code tints it, so a glyph carries",
        " * no colour of its own.  Metrics are the font's own:",
        f" * Coverage is {'antialiased' if antialias else '0 or 255, thresholded at 128'}.",
        f" * ascent {ascent}, descent {descent}, line {height}.",
        " */",
        f"#ifndef {prefix.upper()}_H",
        f"#define {prefix.upper()}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {prefix.upper()}_FIRST {FIRST}U",
        f"#define {prefix.upper()}_LAST {LAST}U",
        f"#define {prefix.upper()}_ASCENT {ascent}U",
        f"#define {prefix.upper()}_DESCENT {descent}U",
        f"#define {prefix.upper()}_HEIGHT {height}U",
        "",
    ]
    for code, ch, advance, width, data in glyphs:
        name = f"{prefix}_{code}"
        lines.append(f"/* {code} {ch!r} advance {advance} */")
        lines.append(f"static const uint8_t {name}[] = {{")
        row = []
        for index, value in enumerate(data):
            row.append(f"{value:4d},")
            if len(row) == 16:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
    lines.append("")
    # ONE GLYPH TYPE FOR EVERY FACE.  The generator used to name the
    # struct after the prefix, which meant two generated fonts had two
    # incompatible types and could not sit in one table - the thing that
    # is needed the moment a desktop offers a font SIZE.
    lines.append("#ifndef TRAIT_GLYPH_DEFINED")
    lines.append("#define TRAIT_GLYPH_DEFINED")
    lines.append("struct trait_glyph {")
    lines.append("    const uint8_t *coverage;")
    lines.append("    uint32_t width;")
    lines.append("    uint32_t advance;")
    lines.append("};")
    lines.append("#endif")
    lines.append("")
    lines.append(f"static const struct trait_glyph {prefix}[] = {{")
    for code, ch, advance, width, _ in glyphs:
        lines.append(f"    {{ {prefix}_{code}, {width}U, {advance}U }},")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif /* {prefix.upper()}_H */")
    out.write_text("\n".join(lines) + "\n")
    lit = sum(1 for _, _, _, _, d in glyphs for v in d if v)
    shades = len({v for _, _, _, _, d in glyphs for v in d})
    if not antialias and shades > 2:
        sys.exit("REFUSED: %d shades in a thresholded font" % shades)
    print(f"wrote {out}: {len(glyphs)} glyphs, {ttf.name} at {size}px, "
          f"line height {height}, {shades} shade(s), {lit} lit pixels")


if __name__ == "__main__":
    main()
