#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-only
"""Turn an X11 bitmap font into the tables the C shell draws text with.

    python3 tools/make-font.py <font.pcf[.gz]> <out.h> <prefix>

THERE IS NO FONT SERVER IN A FRAMEBUFFER.  The C side draws text by
compositing a coverage bitmap per glyph, so the glyphs are unpacked once,
here, ahead of time - the same way the icon planes are made.

The source is a PCF, which is how X has shipped its bitmap fonts since
R6.  That matters more than it sounds.  The earlier version of this
script rasterised DejaVu at 5px and doubled the result, on the theory
that a small outline font with its edges cut off would read as a pixel
font.  It does not.  DejaVu was drawn to be hinted and antialiased; at
5px its stems land between pixels, thresholding drops half of them, and
the doubling turns what is left into confetti.  Misc-Fixed was drawn on
the grid, one pixel at a time, by people who could see the grid.  Every
glyph here is the one its author placed.

Only the printable ASCII range is emitted, because that is what a
desktop puts on screen: a clock, a task name, a menu row, a file name.
A glyph outside it draws nothing rather than a box, and the caller can
see that in the coverage table.
"""
import gzip
import io
import sys
from pathlib import Path

from PIL import Image, PcfFontFile

FIRST, LAST = 32, 126

# TWO GLYPHS THAT ARE NOT IN THE FONT, at the codes after the last.
#
# Misc-Fixed has no full block and no shade, and neither does any other
# X bitmap face here; U+2588 and U+2592 live above the range these were
# drawn for.  A terminal wants both - they are how you draw a picture
# out of characters - and a filled rectangle and a chequer of every
# other pixel are not typefaces, so synthesising them is not the same as
# redrawing somebody's letterforms.  gfetch is what asked.
#
# The shade is the 50% weave X has drawn its root with since before
# there were wallpapers: every other pixel, period two.  Half the ink of
# the block at the same shape, which is what a picture wants for its
# middle when its edge is already solid.
BLOCK = 127
SHADE = 128


def load(path):
    """PCF, gzipped or not.  PcfFontFile wants a seekable file."""
    raw = path.read_bytes()
    if raw[:2] == b"\x1f\x8b":
        raw = gzip.decompress(raw)
    return PcfFontFile.PcfFontFile(io.BytesIO(raw))


def main():
    if len(sys.argv) < 4:
        sys.exit(__doc__.strip().splitlines()[2].strip())
    src = Path(sys.argv[1])
    out = Path(sys.argv[2])
    prefix = sys.argv[3]

    pcf = load(src)
    name = pcf.info.get(b"FONT", b"").decode("latin-1")

    # dst is the glyph's box measured from the baseline origin, so the
    # top edge is negative and the ascent is how far the tallest box
    # reaches above the baseline.  Misc-Fixed is one cell for every
    # character, but nothing here assumes that.
    boxes = [pcf.glyph[c] for c in range(FIRST, LAST + 1) if pcf.glyph[c]]
    if len(boxes) != LAST - FIRST + 1:
        sys.exit("REFUSED: %s is missing printable ASCII" % src.name)
    ascent = max(-box[1][1] for box in boxes)
    descent = max(box[1][3] for box in boxes)
    height = ascent + descent

    glyphs = []
    for code in range(FIRST, LAST + 1):
        step, dst, _, glyph = pcf.glyph[code]
        advance = step[0]
        width = max(advance, dst[2], 1)
        cell = Image.new("L", (width, height), 0)
        cell.paste(glyph.convert("L"), (dst[0], ascent + dst[1]))
        glyphs.append((code, chr(code), advance, width,
                       list(cell.get_flattened_data())))

    # The block, filling the cell the face defines, and the shade,
    # filling every other pixel of it.
    width = glyphs[0][3]
    block = [255] * (width * height)
    shade = [255 if (x + y) % 2 == 0 else 0
             for y in range(height) for x in range(width)]
    glyphs.append((BLOCK, "\u2588", glyphs[0][2], width, block))
    glyphs.append((SHADE, "\u2592", glyphs[0][2], width, shade))

    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-only */",
        "/*",
        " * GENERATED by tools/make-font.py - do not edit.",
        " *",
        f" * {name or src.name}",
        " *",
        " * Printable ASCII only, one coverage byte per pixel.  The",
        " * drawing code tints it, so a glyph carries no colour of its",
        " * own.  A bitmap font has no shades: every byte is 0 or 255.",
        f" * ascent {ascent}, descent {descent}, line {height}.",
        " *",
        " * See assets/fonts/SOURCE.txt for where the bitmaps come from",
        " * and on what terms.",
        " */",
        f"#ifndef {prefix.upper()}_H",
        f"#define {prefix.upper()}_H",
        "",
        "#include <stdint.h>",
        "",
        f"#define {prefix.upper()}_FIRST {FIRST}U",
        f"#define {prefix.upper()}_LAST {SHADE}U",
        f"#define {prefix.upper()}_BLOCK {BLOCK}U",
        f"#define {prefix.upper()}_SHADE {SHADE}U",
        f"#define {prefix.upper()}_ASCENT {ascent}U",
        f"#define {prefix.upper()}_DESCENT {descent}U",
        f"#define {prefix.upper()}_HEIGHT {height}U",
        "",
    ]
    for code, ch, advance, width, data in glyphs:
        lines.append(f"/* {code} {ch!r} advance {advance} */")
        lines.append(f"static const uint8_t {prefix}_{code}[] = {{")
        row = []
        for value in data:
            row.append(f"{value:4d},")
            if len(row) == 16:
                lines.append("    " + "".join(row))
                row = []
        if row:
            lines.append("    " + "".join(row))
        lines.append("};")
    lines.append("")
    # ONE GLYPH TYPE FOR EVERY FACE.  The generator used to name the
    # struct after the prefix, which meant two generated fonts had two
    # incompatible types and could not sit in one table - the thing that
    # is needed the moment a desktop offers a font SIZE.
    lines.append("#ifndef TRAIT_GLYPH_DEFINED")
    lines.append("#define TRAIT_GLYPH_DEFINED")
    lines.append("struct trait_glyph {")
    lines.append("    const uint8_t *coverage;")
    lines.append("    uint32_t width;")
    lines.append("    uint32_t advance;")
    lines.append("};")
    lines.append("#endif")
    lines.append("")
    lines.append(f"static const struct trait_glyph {prefix}[] = {{")
    for code, ch, advance, width, _ in glyphs:
        lines.append(f"    {{ {prefix}_{code}, {width}U, {advance}U }},")
    lines.append("};")
    lines.append("")
    lines.append(f"#endif /* {prefix.upper()}_H */")

    shades = {v for _, _, _, _, d in glyphs for v in d}
    if shades - {0, 255}:
        sys.exit("REFUSED: %d shades in a bitmap font" % len(shades))
    # A blank glyph shipped unnoticed once already: DejaVu's underscore
    # fell one row below the cell and nobody could type a file name.
    blank = [ch for _, ch, _, _, d in glyphs if ch != " " and not any(d)]
    if blank:
        sys.exit("REFUSED: blank glyph(s) %s" % "".join(blank))

    out.write_text("\n".join(lines) + "\n")
    lit = sum(1 for _, _, _, _, d in glyphs for v in d if v)
    print(f"wrote {out}: {len(glyphs)} glyphs from {src.name}, "
          f"line height {height}, {lit} lit pixels")


if __name__ == "__main__":
    main()
