/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-logo.py - do not edit.
 *
 * The characters are openrfs-logo.txt, which is asciiart.eu's
 * converter run over openrfs-mark-flat.png.
 * The colours are computed from that same image on the same
 * grid.  assets/logo/SOURCE.txt records the settings and whose
 * drawing it is.
 */
#ifndef TRAIT_LOGO_H
#define TRAIT_LOGO_H

#define TRAIT_LOGO_ROWS 12U
#define TRAIT_LOGO_COLUMNS 33U

/*
 * The colours are the DRAWING'S, averaged over every pixel
 * that came out body, tongue or eye.  The outline is not here:
 * it is black in the drawing, and black on a black terminal is
 * a line you cannot see, so the C side inks it in the
 * terminal's own foreground and says so.
 */
#define TRAIT_LOGO_BODY 0xB85A55U
#define TRAIT_LOGO_TONGUE 0xD18D95U
#define TRAIT_LOGO_EYE 0xFEFEFEU

static const char *const trait_logo[TRAIT_LOGO_ROWS] = {
    "       \200\200",
    "       \200\177\177\200\200  \200\200\200\200\200 \200\200\200\200\200\200",
    "      \200\177\200\200\177\200\200\177\177 \177\177\177\177\177\177 \177\177\200\200",
    "      \200\177\200\200\200\177\177\177 \177\177\177\177\177\177 \177\177\177\177\200",
    "   \200\177\177\177\200\200\200\200\200\177\177\177\177\177\177\177\177\177\177\177\177\177\200\200    \200\200",
    " \200\177\177\200\200\200\200\200\200\200\200\200\177\177\177\177\177\177\200\200\177\177\177\200\177\200\200\177\177\200\200\200",
    " \200\177\200\200\200\200\200\200\200\200\200\200\200\200\200\177\177\177\177\177\177\177\200\200\200\177\177\177\177\200\200",
    " \200\177\200\200\200\200\200\200\200\200\200\200\200\200\177\177\177\177\177\177\177\177\177\177\177\200\200\200\177\200\200\200",
    "  \200\177\177\200\200\200\200\200\200\200\200\200\200\200\177\177\177\177\177\177\177\177\200\200",
    "    \200\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\177\200\177\177\200\200",
    "      \200\200\200\200\200\200\200\200\200\200\200\200\200 \177\177\177\177\177\177\177\200\200",
    "                       \200\200\200",
};

/* One code per character of the row above: 0 the terminal's own
 * ink, 1 the outline, 2 the body, 3 the tongue, 4 an eye. */
static const char *const trait_logo_ink[TRAIT_LOGO_ROWS] = {
    "000000022",
    "00000002222200222220222222",
    "000000222222244044444404422",
    "000000222222440444444044442",
    "000222222222244444422444222000022",
    "022222222222222222222222222222222",
    "02222222222222222222222222222222",
    "022222222222222233333332222222222",
    "00222222222222222223333322",
    "00002222222222222223333323322",
    "00000022222222222220333333322",
    "00000000000000000000000222",
};

#endif /* TRAIT_LOGO_H */
