/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-logo.py - do not edit.
 *
 * The OpenRFS mark at 32 by 15 characters, reduced from
 * openrfs-mark-512.png.  See assets/logo/SOURCE.txt for
 * whose drawing it is.
 */
#ifndef TRAIT_LOGO_H
#define TRAIT_LOGO_H

#define TRAIT_LOGO_ROWS 15U
#define TRAIT_LOGO_COLUMNS 32U

static const char *const trait_logo[TRAIT_LOGO_ROWS] = {
    "      ##",
    "       ++#",
    "      #+++##      ##",
    "      #++++#  ###  # ####",
    "    #+++++++  #### #  ###",
    "  #+++++++++#  ## #++####",
    " #++++++++++++#+++++++++++  #+#",
    "#++++++++++++++++++++++#++++++#",
    "++++++++++++++##+++++##+++++++#",
    "#++++++++++++++#++++++++++  #+##",
    " ++++++++++++++++++++++++",
    "  ++++#++#+++++++++++++#",
    "    ##++++++++++++++:+++ ++",
    "     #+ ####+####   +:+++++#",
    "                     ++++",
};

#endif /* TRAIT_LOGO_H */
