/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-logo.py - do not edit.
 *
 * The characters AND their colours are openrfs-logo-2026.json,
 * which is coddy.tech's ASCII art generator run over the
 * drawing with Color on and the width at 45.  Nothing here is
 * classified or averaged: every cell is the cell that
 * generator produced, with its colour snapped to the nearest
 * of 15.  assets/logo/SOURCE.txt records the settings and
 * whose drawing it is.
 */
#ifndef TRAIT_LOGO_H
#define TRAIT_LOGO_H

#define TRAIT_LOGO_ROWS 16U
#define TRAIT_LOGO_COLUMNS 45U
#define TRAIT_LOGO_INKS 16U

/*
 * THE MARK'S OWN COLOURS, reduced from the 251 the capture
 * holds to 15 by k-means over the cells that use them.
 * Entry 0 is not a colour: a cell with nothing drawn in it
 * takes the terminal's own foreground.
 */
static const uint32_t trait_logo_ink[TRAIT_LOGO_INKS] = {
    0x000000U,   /* unused: index 0 means the terminal's ink */
    0x165463U,
    0x6D93A1U,
    0x9F0000U,
    0xAA1E1EU,
    0xB80101U,
    0xC14748U,
    0xC70000U,
    0xD07171U,
    0xD30000U,
    0xD5A7A6U,
    0xDB2F2FU,
    0xDC0000U,
    0xE60000U,
    0xEDD6D6U,
    0xEF0000U,
};

static const char *const trait_logo[TRAIT_LOGO_ROWS] = {
    "                        *####*+.",
    " .:                   :####**####+",
    " +##=                -#############-",
    " #####*             -##################+.",
    ".#######:          =###############***###*",
    " *#######-        .*########**#=:::+**###-*.",
    "  ###*####-     :###########*#=:*+%*+***###-",
    "   +#######+.-*##############**--*+=*****#=-",
    "  .########*#####################*####***##.",
    "  ########*. =#############################-",
    " .#######.   --: *####################*+++*-",
    " .#####=        *####***############*####*",
    " +###+        .*#####**################*#-",
    "=#*.        :##########+   :######*-",
    "            +======-.        =##*",
    "                               .=+",
};

/* One hex digit per character of the row above: an index into
 * trait_logo_ink, and 0 where nothing is drawn. */
static const char *const trait_logo_at[TRAIT_LOGO_ROWS] = {
    "000000000000000000000000B9CCC96E",
    "0EA0000000000000000000E7CCDFFC9C76",
    "08778000000000000000089CC9DC7775575A",
    "0579974000000000000087997333557735CCC996E",
    "E57CC995A00000000008575557999CDDCCDFFFDC54",
    "06CFDDC95A00000000E47779CCCFFF72AEA6FFDD9A6E",
    "0059DFDC97A00000A7779CD9DDDCFD8A1211BFFFF41A",
    "00069CC99996EABCCCCCC9CCDDDDDFBA2122FFFFF42A",
    "00E77999CCDFFFDDCCC979C9C9DCCDDDDDDDDDFFFD3E",
    "00579CDDC9BE0857555577779C9CCCCDDDDDCCCCDD7A",
    "0E37DFDC7E000A8E047CCDDDC999CCCCCC7779CBBBBA",
    "0E59FF9800000000659CDFFFFD97D9555559444446",
    "069C9600000000E47CDDDFFDC9533333333359DDC8",
    "874E00000000E37CCDDDD956000E577755BA",
    "0000000000006888888AE000000008774",
    "0000000000000000000000000000000E86",
};

#endif /* TRAIT_LOGO_H */
