/* SPDX-License-Identifier: GPL-3.0-only */
/* GENERATED by tools/make-relief.py - do not edit. */
#ifndef TRAIT_RELIEF_H
#define TRAIT_RELIEF_H

/*
 * fvwm bevels every frame in two colours it computes from the
 * background with GetHilite() and GetShadow().  This is those
 * two functions, run over every ground this desktop bevels, so
 * the relief is fvwm's arithmetic rather than a pair of
 * colours that looked about right beside the first.
 *
 * Each name expands to THREE colours - ground, lit side, shadow
 * side - in that order, so a palette names a frame once.
 */

/* Clearlooks' own title bar */
#define TRAIT_RELIEF_CLEARLOOKS_ACTIVE \
    0x5B6472U, 0x7D8BA1U, 0x303236U

/* Clearlooks' unfocused title bar */
#define TRAIT_RELIEF_CLEARLOOKS_IDLE \
    0x3B3F46U, 0x4F5765U, 0x1E1F21U

/* Adwaita's own title bar */
#define TRAIT_RELIEF_ADWAITA_ACTIVE \
    0x5C616CU, 0x7F8798U, 0x303134U

/* Adwaita's unfocused title bar */
#define TRAIT_RELIEF_ADWAITA_IDLE \
    0x3C4048U, 0x505868U, 0x1F2022U

/* Adwaita-dark's own title bar */
#define TRAIT_RELIEF_ADWAITA_DARK_ACTIVE \
    0x2F2F2FU, 0x414141U, 0x171717U

/* Adwaita-dark's unfocused title bar */
#define TRAIT_RELIEF_ADWAITA_DARK_IDLE \
    0x262626U, 0x929292U, 0x676767U

/* fvwm's HilightColor #bebebe blue - the focused window */
#define TRAIT_RELIEF_OPENRFS_ACTIVE \
    0x0000FFU, 0x6666FFU, 0x1F1F5FU

/* fvwm's Style "*" Color #bebebe/darkred - every other window */
#define TRAIT_RELIEF_OPENRFS_IDLE \
    0x8B0000U, 0xC20000U, 0x341111U

/* fvwm's MenuStyle #4d4d4d #bebebe #e7e7e7 - the root menu */
#define TRAIT_RELIEF_MENU \
    0xBEBEBEU, 0xFFFFFFU, 0x5F5F5FU

#endif /* TRAIT_RELIEF_H */
