/* SPDX-License-Identifier: GPL-3.0-only */
/*
 * GENERATED by tools/make-gears.py - do not edit.
 *
 * glxgears' three gears, projected.  Each is one closed outline
 * and one bore, in view units of 1/1024, on the plane behind the
 * gear; `sweep` is the vector from that plane to the lit face,
 * so the solid is the outline swept along it.  See
 * assets/gears/SOURCE.txt.
 */
#ifndef TRAIT_GEARS_ART_H
#define TRAIT_GEARS_ART_H

#include <stdint.h>

#define TRAIT_GEARS_UNIT 1024L
#define TRAIT_GEARS_COUNT 3U

/* The whole scene, so a caller can fit it to a screen. */
#define TRAIT_GEARS_MIN_X -6762L
#define TRAIT_GEARS_MAX_X 5345L
#define TRAIT_GEARS_MIN_Y -5820L
#define TRAIT_GEARS_MAX_Y 6855L

/* green: 40 outline points, 48 in the bore */
static const int32_t trait_gears_green_outline[] = {
    3682L, 1041L, 4321L, 667L, 4295L, 318L, 3629L, 313L,
    3541L, 100L, 3923L, -584L, 3711L, -812L, 3097L, -376L,
    2901L, -468L, 2881L, -1199L, 2563L, -1219L, 2237L, -509L,
    2008L, -445L, 1593L, -945L, 1291L, -750L, 1377L, -36L,
    1202L, 160L, 551L, 82L, 380L, 418L, 845L, 862L,
    792L, 1115L, 153L, 1490L, 179L, 1839L, 845L, 1844L,
    933L, 2057L, 551L, 2740L, 763L, 2968L, 1377L, 2533L,
    1573L, 2624L, 1593L, 3356L, 1911L, 3376L, 2237L, 2666L,
    2466L, 2601L, 2881L, 3102L, 3183L, 2906L, 3097L, 2193L,
    3272L, 1997L, 3923L, 2075L, 4094L, 1738L, 3629L, 1294L,
};
static const int32_t trait_gears_green_bore[] = {
    2675L, 1067L, 2680L, 1003L, 2678L, 941L, 2668L, 881L,
    2651L, 824L, 2627L, 772L, 2596L, 725L, 2559L, 684L,
    2516L, 649L, 2469L, 622L, 2417L, 603L, 2363L, 592L,
    2306L, 589L, 2249L, 595L, 2191L, 609L, 2134L, 631L,
    2078L, 661L, 2026L, 697L, 1976L, 741L, 1932L, 790L,
    1893L, 844L, 1859L, 902L, 1832L, 963L, 1812L, 1026L,
    1799L, 1090L, 1794L, 1153L, 1796L, 1216L, 1806L, 1276L,
    1823L, 1332L, 1847L, 1385L, 1878L, 1432L, 1915L, 1473L,
    1958L, 1507L, 2005L, 1534L, 2057L, 1553L, 2111L, 1565L,
    2168L, 1567L, 2226L, 1562L, 2283L, 1548L, 2341L, 1526L,
    2396L, 1496L, 2449L, 1459L, 2498L, 1416L, 2542L, 1367L,
    2582L, 1313L, 2615L, 1255L, 2642L, 1194L, 2662L, 1131L,
};
/* red: 80 outline points, 48 in the bore */
static const int32_t trait_gears_red_outline[] = {
    320L, 1659L, 929L, 1210L, 894L, 891L, 231L, 857L,
    162L, 605L, 648L, -7L, 521L, -281L, -157L, -82L,
    -298L, -283L, 17L, -999L, -189L, -1200L, -814L, -788L,
    -1014L, -919L, -901L, -1669L, -1165L, -1777L, -1678L, -1191L,
    -1916L, -1240L, -2016L, -1950L, -2313L, -1955L, -2662L, -1253L,
    -2916L, -1214L, -3219L, -1815L, -3520L, -1717L, -3672L, -968L,
    -3917L, -845L, -4393L, -1277L, -4668L, -1086L, -4608L, -362L,
    -4819L, -168L, -5422L, -390L, -5644L, -123L, -5378L, 503L,
    -5535L, 751L, -6206L, 761L, -6354L, 1077L, -5907L, 1545L,
    -5995L, 1821L, -6667L, 2062L, -6727L, 2396L, -6143L, 2660L,
    -6153L, 2937L, -6762L, 3386L, -6727L, 3705L, -6064L, 3740L,
    -5995L, 3991L, -6480L, 4604L, -6354L, 4877L, -5676L, 4678L,
    -5535L, 4880L, -5850L, 5596L, -5644L, 5797L, -5019L, 5384L,
    -4819L, 5515L, -4932L, 6265L, -4668L, 6374L, -4155L, 5788L,
    -3917L, 5836L, -3817L, 6546L, -3520L, 6552L, -3170L, 5850L,
    -2916L, 5810L, -2614L, 6411L, -2313L, 6313L, -2161L, 5564L,
    -1916L, 5441L, -1440L, 5874L, -1165L, 5682L, -1225L, 4959L,
    -1014L, 4764L, -411L, 4986L, -189L, 4719L, -455L, 4093L,
    -298L, 3845L, 373L, 3836L, 521L, 3520L, 74L, 3052L,
    162L, 2776L, 835L, 2535L, 894L, 2201L, 310L, 1937L,
};
static const int32_t trait_gears_red_bore[] = {
    -2030L, 2123L, -2037L, 1999L, -2060L, 1880L, -2097L, 1768L,
    -2148L, 1665L, -2213L, 1573L, -2289L, 1494L, -2377L, 1428L,
    -2473L, 1377L, -2577L, 1342L, -2687L, 1323L, -2801L, 1321L,
    -2916L, 1336L, -3032L, 1367L, -3146L, 1414L, -3256L, 1476L,
    -3360L, 1552L, -3456L, 1641L, -3543L, 1742L, -3620L, 1851L,
    -3684L, 1969L, -3736L, 2092L, -3773L, 2218L, -3796L, 2346L,
    -3803L, 2473L, -3796L, 2597L, -3773L, 2716L, -3736L, 2828L,
    -3684L, 2931L, -3620L, 3023L, -3543L, 3102L, -3456L, 3168L,
    -3360L, 3219L, -3256L, 3254L, -3146L, 3273L, -3032L, 3275L,
    -2916L, 3260L, -2801L, 3229L, -2687L, 3182L, -2577L, 3120L,
    -2473L, 3044L, -2377L, 2955L, -2289L, 2855L, -2213L, 2745L,
    -2148L, 2628L, -2097L, 2505L, -2060L, 2378L, -2037L, 2250L,
};
/* blue: 40 outline points, 48 in the bore */
static const int32_t trait_gears_blue_outline[] = {
    -1551L, -3165L, -874L, -3347L, -809L, -3707L, -1415L, -3919L,
    -1441L, -4161L, -919L, -4735L, -1054L, -5031L, -1724L, -4780L,
    -1879L, -4933L, -1712L, -5679L, -1996L, -5798L, -2474L, -5180L,
    -2699L, -5185L, -2950L, -5820L, -3275L, -5716L, -3378L, -4968L,
    -3587L, -4823L, -4160L, -5103L, -4401L, -4816L, -4090L, -4223L,
    -4203L, -3984L, -4880L, -3802L, -4946L, -3442L, -4339L, -3230L,
    -4313L, -2988L, -4835L, -2414L, -4700L, -2118L, -4030L, -2369L,
    -3875L, -2216L, -4042L, -1470L, -3758L, -1351L, -3280L, -1969L,
    -3055L, -1963L, -2804L, -1329L, -2479L, -1433L, -2377L, -2181L,
    -2168L, -2326L, -1594L, -2046L, -1353L, -2333L, -1664L, -2926L,
};
static const int32_t trait_gears_blue_bore[] = {
    -1832L, -3252L, -1778L, -3415L, -1742L, -3581L, -1725L, -3747L,
    -1729L, -3910L, -1752L, -4067L, -1794L, -4216L, -1855L, -4354L,
    -1933L, -4478L, -2027L, -4587L, -2136L, -4679L, -2258L, -4752L,
    -2390L, -4804L, -2530L, -4836L, -2677L, -4846L, -2827L, -4834L,
    -2978L, -4801L, -3127L, -4746L, -3271L, -4672L, -3409L, -4579L,
    -3538L, -4469L, -3656L, -4343L, -3760L, -4204L, -3849L, -4055L,
    -3922L, -3897L, -3977L, -3733L, -4012L, -3567L, -4029L, -3402L,
    -4026L, -3239L, -4003L, -3081L, -3960L, -2933L, -3900L, -2795L,
    -3821L, -2670L, -3727L, -2561L, -3618L, -2470L, -3497L, -2397L,
    -3364L, -2344L, -3224L, -2313L, -3077L, -2303L, -2927L, -2315L,
    -2777L, -2348L, -2628L, -2402L, -2483L, -2477L, -2345L, -2570L,
    -2216L, -2680L, -2098L, -2806L, -1994L, -2945L, -1905L, -3094L,
};

struct trait_gears_shape {
    const int32_t *outline;   /* x, y interleaved, view units */
    uint32_t outline_points;
    const int32_t *bore;
    uint32_t bore_points;
    int32_t sweep_x;          /* back plane -> lit face */
    int32_t sweep_y;
    uint32_t face;            /* the lit face's colour */
    uint32_t side;            /* everything the light misses */
};

/* Farthest first: this is the order they are painted in. */
static const struct trait_gears_shape trait_gears[TRAIT_GEARS_COUNT] = {
    { trait_gears_green_outline, 40U,
      trait_gears_green_bore, 48U,
      1024L, 607L, 0x55FF55U, 0x00AA00U },
    { trait_gears_red_outline, 80U,
      trait_gears_red_bore, 48U,
      512L, 303L, 0xE8564BU, 0x9E1B1BU },
    { trait_gears_blue_outline, 40U,
      trait_gears_blue_bore, 48U,
      256L, 152L, 0x5555FFU, 0x0000AAU },
};

#endif /* TRAIT_GEARS_ART_H */
